---

# Add apt keys
- name: add key for ppa python repository
  apt_key: keyserver=keyserver.ubuntu.com id=DB82666C state=present
  become: yes
  become_user: root
  become_method: sudo

# Add extra repositories
- name: Add ppa python repository
  apt_repository: repo='deb http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu {{ ansible_distribution_release }} main' state=present update_cache=yes
  become: yes
  become_user: root
  become_method: sudo

# Update python version
- name: ensure python2.7 tatest  is installed
  apt:
    pkg: python2.7
    state: latest
    install_recommends: no
  become: yes
  become_user: root
  become_method: sudo

- name: install pip
  sudo: yes
  apt: name=python-pip update_cache=yes

- name: install docker-py
  sudo: yes
  pip: name=docker-py version=1.7.2