---
- name: install artifactory container app
  sudo: yes
  docker:
     name: artifactory
     image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss
     state: started
     ports:
        - "80:80"
        - "8081:8081"
        - "443:443"
        - "5000-5002:5000-5002"